### ISSUE TITLE
Add homepage of topics for the Forum showing a list of cards of topics

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/demos-multiforum#6]
Should be something like:

<img width="723" alt="screen shot 2016-04-06 at 16 41 10" src="https://cloud.githubusercontent.com/assets/558901/14330319/6b1274e6-fc16-11e5-8790-2711f1d62837.png">

**Comment by mjlescano** [comment]
@franciclo, just pushed the homepage with a dummy view, and I'm passing you the ball with the design implementations. Use the branch `add-forum-homepage`.

**Comment by franciclo** [comment]
ok

**Comment by mjlescano** [comment]
Some references:
http://bsasnosevende.democracyos.org/ 👉 https://github.com/DemocraciaEnRed/bsasnosevende
http://bahiablanca.democracyos.org/ 👉 https://github.com/DemocraciaEnRed/bahiablanca
